Repository amp-labs/connectors, pull requests merged in 2024-08, with the labels that each got.

#756 feat: Deep connector Jira (AuthInfo)
  atlassian/authmetadata.go
  atlassian/authmetadata_test.go
  atlassian/authmetamodel.go
  atlassian/client.go
  atlassian/connector.go
  atlassian/errors.go
  atlassian/modules.go
  atlassian/params.go
  atlassian/test/cloud-id.json
  atlassian/url.go
  docusign/authmetamodel.go
  test/atlassian/auth-metadata/main.go
  test/atlassian/connector.go
Labels: auth-metadata-connector

#710 feat: Deep connector Jira (Read)
  atlassian/authmetadata.go
  atlassian/connector.go
  atlassian/parse.go
  atlassian/read.go
  atlassian/read_test.go
  atlassian/test/jql-error.json
  atlassian/test/path-not-found.json
  atlassian/test/read-issues.json
  providers/atlassian.go
  test/atlassian/auth-metadata/main.go
  test/atlassian/read/main.go
Labels: read-connector

#755 feat: Deep connector Jira (Write)
  atlassian/delete.go
  atlassian/delete_test.go
  atlassian/errors.go
  atlassian/test/create-issue-invalid-project.json
  atlassian/test/create-issue-invalid-type.json
  atlassian/test/create-issue.json
  atlassian/test/delete-issue-not-found.json
  atlassian/write.go
  atlassian/write_test.go
  test/atlassian/write-delete/main.go
Labels: write-connector

#799 feat: Deep connector Jira (Metadata)
  atlassian/metadata.go
  atlassian/metadataFields.go
  atlassian/metadata_test.go
  atlassian/test/issue-metadata.json
  test/atlassian/metadata/main.go
Labels: object-metadata-connector

#845 feat: Enable proxy: Seismic
  providers/seismic.go
Labels: auth-integration-testing

#868 feat: Enable proxy: SendGrid
  providers/sendGrid.go
Labels: auth-integration-testing

#802 feat: Enable proxy: Pipeliner
  providers/pipeliner.go
Labels: auth-integration-testing

#865 feat: Enable proxy: Apollo connector
  providers/apollo.go
Labels: integration-testing

#864 feat: Enable proxy: Nutshell connector
  providers/nutshell.go
Labels: integration-testing

#863 feat: enable proxy blueshift
  providers/blueshift.go
Labels: auth-integration-testing

#861 feat: enable proxy bird
  providers/bird.go
Labels: auth-integration-testing

#859 feat: Enable proxy: Rebilly connectors
  providers/rebilly.go
Labels: integration-testing

#858 feat: enable proxy brevo
  providers/brevo.go
Labels: auth-integration-testing

#854 feat: Enable proxy: paddle connector
  providers/paddle.go
Labels: integration-testing

#851 feat: Add G2 connector
  providers/g2.go
Labels: auth-connector

#844 feat: Enable read+write: Atlassian
  providers/atlassian.go
Labels: integration-testing

#891 feat: Update Zendesk Chat Oauth2 config
  providers/zendesk.go
Labels: auth-connector

#881 feat: Enable proxy: G2
  providers/g2.go
Labels: auth-integration-testing

#879 feat: Enable proxy: Anthropic
  providers/anthropic.go
Labels: auth-integration-testing

#878 feat: Enable proxy: OpenAI
  providers/openAI.go
Labels: auth-integration-testing

#874 feat: enable proxy: Guru connector
  providers/guru.go
Labels: integration-testing

#873 feat: enable proxy: Jotform connector
  providers/jotform.go
Labels: integration-testing

#896 feat: Add Smartlead connector
  providers/smartlead.go
Labels: auth-connector

#867 feat: Enable proxy: Hive connector
  providers/hive.go
Labels: integration-testing

#904 feat: enable proxy: Insightly connector
  providers/insightly.go
Labels: integration-testing

#905 feat: enable proxy marketo
  providers/marketo.go
Labels: auth-integration-testing

#903 feat: Enable proxy: Smartlead
  providers/smartlead.go
Labels: auth-integration-testing

#916 [auto] Update openapi dependency
  providers/types.gen.go
Labels: openapi

#901 feat: Deep connector Smartlead (Read)
  smartlead/client.go
  smartlead/connector.go
  smartlead/errors.go
  smartlead/params.go
  smartlead/parse.go
  smartlead/read.go
  smartlead/read_test.go
  smartlead/test/read-campaign-empty.json
  smartlead/test/read-campaign.json
  smartlead/test/read-invalid-path.html
  smartlead/url.go
  test/smartlead/connector.go
  test/smartlead/read/main.go
Labels: read-connector

#902 feat: Add Deep Connector Smartlead (Write)
  common/handy/set.go
  common/types.go
  smartlead/connector.go
  smartlead/delete.go
  smartlead/delete_test.go
  smartlead/errors.go
  smartlead/test/delete-campaign.json
  smartlead/test/delete-not-found-resource.json
  smartlead/test/write-account-missing.json
  smartlead/test/write-account-new.json
  smartlead/test/write-campaign-new.json
  smartlead/test/write-client-duplicate.json
  smartlead/test/write-client-new.json
  smartlead/test/write-invalid-field.json
  smartlead/write.go
  smartlead/write_test.go
  test/smartlead/write-delete/main.go
  test/utils/dump.go
Labels: write-connector

#909 feat: Add Deep connector Smartlead (Metadata)
  smartlead/metadata.go
  smartlead/metadata/schemas.json
  smartlead/metadata/scraping.go
  smartlead/metadata_test.go
  test/smartlead/metadata/main.go
Labels: object-metadata-connector

#917 fix: DisplayNames for Salesloft schemas.json
  salesloft/metadata/index.json
  salesloft/metadata/schemas.json
  salesloft/metadata_test.go
  scripts/scrapper/salesloft/metadata/main.go
Labels: bug

#924 feat: Enable read+write: Smartlead
  providers/smartlead.go
Labels: integration-testing

#928 [auto] Update openapi dependency
  providers/types.gen.go
Labels: openapi

#884 feat: Enable proxy: Customer Journeys App
  providers/customer.go
Labels: auth-integration-testing

#943 feat: enable snapchatAds connector
  providers/snapchatAds.go
Labels: auth-integration-testing

#940 feat: Enable proxy: Customer Journeys Track
  providers/customer.go
Labels: auth-integration-testing

#937 Feat/Geckoboard enable proxy
  providers/geckoboard.go
Labels: auth-integration-testing

#945 Feat: Enable Mixmax proxy
  providers/mixmax.go
Labels: auth-integration-testing

#914 feat: Add Instantly connector
  providers/instantly.go
Labels: auth-connector

#963 Feat: Enable stripe proxy
  providers/stripe.go
Labels: auth-integration-testing

#975 feat: Update OpenAPI metadata tool; update Intercom OpenAPI
  intercom/metadata/README.md
  intercom/metadata/index.json
  intercom/metadata/schemas.json
  intercom/metadata/scraping.go
  intercom/metadata_test.go
  intercom/openapi/api.intercom.io.yaml
  intercom/openapi/file.go
  pipeliner/metadata/scraping.go
  scripts/openapi/intercom/metadata/main.go
  scripts/openapi/pipeliner/metadata/main.go
  scripts/openapi/zendesksupport/metadata/main.go
  scripts/scrapper/intercom/metadata/main.go
  scripts/scrapper/zendesksupport/metadata/main.go
  tools/fileconv/api3/README.md
  tools/fileconv/api3/aliases.go
  tools/fileconv/api3/models.go
  tools/fileconv/api3/queries.go
  tools/fileconv/api3/strategy.go
  zendesksupport/metadata/schemas.json
  zendesksupport/metadata_test.go
Labels: enhancement, openapi
