Repository amp-labs/connectors, pull requests merged in 2024-06, with the labels that each got.

#459 feat: Enable proxy: Attio
  providers/catalog.go
Labels: auth-integration-testing

#460 feat: Enable proxy: Wrike
  providers/catalog.go
Labels: auth-integration-testing

#369 feat: Enable proxy: Pipedrive
  providers/catalog.go
Labels: auth-integration-testing

#420 feat: enable AWeber proxy connector
  providers/catalog.go
Labels: auth-integration-testing

#432 feat: Add Github Auth Connector
  common/header.go
  common/oauth.go
  providers/catalog.go
  scripts/proxy/proxy.go
Labels: auth-connector

#385 feat: Enable proxy: Drift
  providers/catalog.go
Labels: auth-integration-testing

#431 feat: Add Gong Read connector
  connectors.go
  go.mod
  go.sum
  gong/README.md
  gong/client.go
  gong/connector.go
  gong/errors.go
  gong/methods.go
  gong/params.go
  gong/parse.go
  gong/provider.go
  gong/read.go
  gong/read_test.go
  gong/string.go
  gong/test/read.json
  gong/test/read_cursor.json
  test/gong/read/read.go
  utils/credentials.go
Labels: read-connector

#373 feat: Enable proxy: CapsuleCRM
  providers/catalog.go
Labels: auth-integration-testing

#470 feat: Enable proxy: Facebook Ads Manager
  providers/catalog.go
Labels: auth-integration-testing

#450 feat: Add Basecamp auth connector
  providers/catalog.go
Labels: auth-connector

#456 feat: Add Acuity Scheduling Auth connector
  providers/catalog.go
Labels: auth-connector

#250 feat: Add sharePoint auth connector
  providers/catalog.go
Labels: auth-connector

#483 fix: add AuthorizationCode for missing Grant Types
  providers/catalog.go
  providers/types.gen.go
Labels: bug

#479 fix: pass API version Header for all Intercom methods
  intercom/connector.go
  intercom/delete.go
  intercom/delete_test.go
  intercom/read.go
  intercom/read_test.go
  intercom/write.go
  intercom/write_test.go
  test/utils/mockutils/server.go
Labels: bug

#412 Feat/ Formstack: Enable Proxy
  providers/catalog.go
Labels: auth-integration-testing

#491 Iterable:add connector
  providers/catalog.go
Labels: auth-connector

#498 fix: set Github ExplicitScopesRequired to true
  providers/catalog.go
Labels: bug, auth-connector

#551 feat: Add Blueshift auth connector
  providers/catalog.go
Labels: auth-connector

#552 feat: Add BlueshiftEU auth connector
  providers/catalog.go
Labels: auth-connector

#553 Mixmax: Add a connector
  providers/catalog.go
Labels: auth-connector

#533 feat: Add MessageBird auth connector
  providers/catalog.go
Labels: auth-connector

#545 feat: Add Customer.io Data Pipelines connector
  providers/catalog.go
  scripts/proxy/proxy.go
Labels: auth-connector

#528 feat: Add OpenAI connector
  providers/catalog.go
Labels: auth-connector

#537 feat: Add Anthropic connector
  providers/catalog.go
Labels: auth-connector

#550 feat: Add Hunter connector
  providers/catalog.go
  scripts/proxy/proxy.go
Labels: auth-connector

#455 feat: enable LinkedIn Ads Manager proxy connector
  providers/catalog.go
Labels: auth-integration-testing

#496 feat: Add Domo Auth connector
  providers/catalog.go
Labels: auth-connector

#506 feat: Add Marketo auth connector
  providers/catalog.go
Labels: auth-connector

#544 feat: Add Guru connector
  providers/catalog.go
Labels: auth-connector

#536 fix: set Github ExplicitScopesRequired to true
  providers/catalog.go
Labels: bug, auth-connector

#546 feat: Add Customer.io Journeys App connector
  providers/catalog.go
Labels: auth-connector

#557 feat: Add Brevo auth connector
  providers/brevo.go
Labels: auth-connector

#573 feat: Add Amplitude connector
  providers/amplitude.go
  scripts/proxy/proxy.go
Labels: auth-connector

#572 feat: Add SendGrid auth connector
  providers/sendGrid.go
Labels: auth-connector

#586 fix: Panic thrown by DynamicsCRM.Metadata, change XML lib
  .github/PULL_REQUEST_TEMPLATE/proxy_connector.md
  common/xml.go
  common/xquery/queries.go
  dynamicscrm/metadata.go
  dynamicscrm/metadata_test.go
  go.mod
  go.sum
  providers/dynamics.go
  salesforce/metadataApi.go
  test/dynamicscrm/connector.go
  test/dynamicscrm/metadata/main.go
  tools/connectorgen/template/test/connector.go.tmpl
  utils/credentials.go
Labels: bug

#601 feature: Add Oauth2 Password grant type
  providers/types.gen.go
  providers/types.yaml
  providers/utils.go
  scripts/oauth/token.go
  scripts/proxy/proxy.go
Labels: enhancement

#588 fix: set Github ExplicitScopesRequired to true
  providers/domo.go
Labels: bug, auth-connector

#531 feat: Add Stripe connector
  providers/stripe.go
Labels: auth-connector

#555 feat: Add Salesflare connector
  providers/salesflare.go
Labels: auth-connector

#608 feat: Add Gorgias connector
  providers/gorgias.go
Labels: auth-connector
