Repository amp-labs/connectors, pull requests merged in 2024-05, with the labels that each got.

#268 Gong workspace substitution removal
  providers/catalog.go
  providers/catalog_test.go
Labels: enhancement

#334 Add Campaign Monitor Auth Connector
  providers/catalog.go
  providers/catalog_test.go
Labels: auth-connector

#379 feat: Enable proxy: Figma
  providers/catalog.go
Labels: auth-integration-testing

#374 feat: Enable proxy: Smartsheet
  providers/catalog.go
Labels: auth-integration-testing

#389 feat: Add Pinterest Auth connector
  providers/catalog.go
Labels: auth-connector

#399 feat: Add Aha! connector
  .github/PULL_REQUEST_TEMPLATE/new_connector.md
  providers/catalog.go
Labels: auth-connector

#233 feat: Add Formstack Connector
  providers/catalog.go
Labels: auth-connector

#390 CloseCRM auth connector update
  providers/catalog.go
Labels: auth-connector

#393 Zoho CRM auth connector update
  providers/catalog.go
Labels: auth-connector

#372 feat: Enable proxy: ZohoCRM
  providers/catalog.go
Labels: auth-integration-testing

#328 feat: Add Snapchat Ads Auth connector
  providers/catalog.go
Labels: auth-connector

#407 feat: Enable Microsoft proxy connector
  providers/catalog.go
Labels: auth-integration-testing

#405 feat: Enable proxy: Keap
  providers/catalog.go
Labels: auth-integration-testing

#404 Aircall: Enable Proxy
  providers/catalog.go
Labels: auth-integration-testing

#402 feat: Enable proxy: Copper CRM
  providers/catalog.go
Labels: auth-integration-testing

#409 fix: use Embed of static Schema for Intercom.ListObjectMetadata
  intercom/metadata/scrapping.go
  providers/catalog.go
Labels: bug

#410 fix: Intercom ObjectNames match Read and Metadata methods
  common/scrapper/models.go
  intercom/metadata/schemas.json
  intercom/metadata_test.go
  scripts/scrapper/intercom/metadata/main.go
  test/intercom/metadata/main.go
Labels: bug

#421 feat: Intercom.ListMetadata return custom data fields
  common/naming/plural.go
  common/naming/singular.go
  common/scrapper/convertors.go
  common/scrapper/models.go
  intercom/metadata.go
  intercom/metadata_test.go
  intercom/read.go
  intercom/test/metadata-attributes-company.json
  intercom/test/unsupported-model.json
  test/intercom/metadata/main.go
Labels: enhancement, object-metadata-connector

#394 Feat/Add Instagram Connector
  providers/catalog.go
Labels: auth-connector

#429 add: Module naming; support Singular/Plural strings
  common/naming/plural.go
  common/naming/singular.go
  common/naming/singular_test.go
Labels: enhancement

#419 Wrike auth connector update
  providers/catalog.go
Labels: auth-connector

#403 Keap auth connector update
  providers/catalog.go
Labels: auth-connector

#428 Pipedrive auth connector update
  providers/catalog.go
Labels: auth-connector

#413 feat: enable Pinterest proxy support
  providers/catalog.go
Labels: auth-integration-testing

#435 CapsuleCRM auth connector update
  providers/catalog.go
Labels: auth-connector

#387 feat: Enable proxy: CloseCRM
  providers/catalog.go
Labels: auth-integration-testing

#449 feat: Add TeamleaderCRM Auth connector
  providers/catalog.go
Labels: auth-connector

#451 feat: Enable proxy: Aha!
  providers/catalog.go
Labels: auth-integration-testing

#452 feat: Add Seismic auth connector
  providers/catalog.go
Labels: auth-connector

#434 feat: enable proxy: gong
  providers/catalog.go
Labels: auth-integration-testing

#408 feat: Add ServiceNow Auth connector
  providers/catalog.go
Labels: auth-connector
