Repository amp-labs/connectors, pull requests merged in 2024-07, with the labels that each got.

#619 feat: Add RedditAds auth connector
  providers/redditAds.go
Labels: auth-connector

#634 clean: switch to ajson wrapper (Outreach deep connector)
  outreach/parse.go
Labels: enhancement

#607 feat: add pipeliner connector
  providers/pipeliner.go
Labels: auth-connector

#584 feat: Deep connector Gong (ListMetadata)
  gong/metadata.go
  gong/metadata/schemas.json
  gong/metadata/scrapping.go
  gong/metadata_test.go
  test/gong/metadata/main.go
Labels: object-metadata-connector

#660 feat: Add Power BI auth connector
  providers/powerBI.go
Labels: auth-connector

#665 feat: Add Rebilly Connector
  providers/rebilly.go
Labels: auth-connector

#648 feat: Add Coda connector
  providers/coda.go
  scripts/proxy/proxy.go
Labels: auth-connector

#567 feat: add Jotform connector
  providers/jotform.go
Labels: auth-connector

#615 [ENG-1257] define: CatalogVariable type for substitution
  .github/PULL_REQUEST_TEMPLATE/new_connector.md
  README.md
  common/paramsbuilder/params.go
  common/paramsbuilder/variables.go
  common/paramsbuilder/variables_test.go
  connector/connector.go
  docusign/connector.go
  dynamicscrm/connector.go
  examples/auth_connectors/salesforce/salesforce.go
  examples/deep_connectors/salesforce/salesforce.go
  gong/connector.go
  hubspot/connector.go
  hubspot/modules.go
  hubspot/params.go
  intercom/connector.go
  outreach/connector.go
  providers/utils.go
  providers/utils_test.go
  salesforce/connector.go
  salesloft/connector.go
  scripts/oauth/token.go
  scripts/proxy/proxy.go
Labels: enhancement

#563 feat: Add Hive connector
  providers/hive.go
Labels: auth-connector

#532 feat: Add Apollo connector
  providers/apollo.go
Labels: auth-connector

#534 feat: Add Insightly auth connector
  providers/insightly.go
Labels: auth-connector

#632 feat: Add Crunchbase auth connector
  providers/crunchbase.go
Labels: auth-connector

#669 feat: Add Paddle Connector
  providers/paddle.go
Labels: auth-connector

#671 feat: Add ChargeOver connector
  providers/chargeOver.go
Labels: auth-connector

#495 Add google ads connector
  providers/google.go
Labels: auth-connector

#672 fix: DynamicsCRM ListObjectMetadata accepts plural ObjectName
  common/naming/plural.go
  dynamicscrm/metadata.go
  dynamicscrm/metadata_test.go
  dynamicscrm/test/metadata.xml
  test/dynamicscrm/metadata/main.go
  test/dynamicscrm/read/main.go
  test/dynamicscrm/write-delete/main.go
  test/utils/mockutils/metadataResult.go
Labels: bug

#681 feat: enable acuityScheduling proxy support
  providers/acuityScheduling.go
Labels: auth-integration-testing

#678 feat: Deep connector Zendesk Support (Write)
  test/utils/mockutils/checks.go
  test/zendesksupport/write-delete/main.go
  zendesksupport/delete.go
  zendesksupport/delete_test.go
  zendesksupport/errors.go
  zendesksupport/read_test.go
  zendesksupport/test/create-brand.json
  zendesksupport/test/duplicate-error.json
  zendesksupport/test/missing-parameter.json
  zendesksupport/test/record-validation.json
  zendesksupport/test/server-error.json
  zendesksupport/write.go
  zendesksupport/write_test.go
Labels: write-connector

#685 feat: Add CallRail connector
  providers/callRail.go
Labels: auth-connector

#651 feat: Add Chargebee auth connector
  providers/chargebee.go
Labels: auth-connector

#686 feat: Enable proxy: getResponse
  providers/getResponse.go
Labels: auth-integration-testing

#695 feat: Enable proxy: Discord connector
  providers/discord.go
Labels: auth-integration-testing

#702 feat: Enable proxy: ServiceNow connector
  providers/serviceNow.go
Labels: auth-integration-testing

#694 created separate file for teamwork and updated tokenmetadatafields
  providers/teamwork.go
Labels: auth-connector

#493 feat: Enable proxy: Teamleader CRM
  providers/teamleaderCRM.go
Labels: auth-integration-testing

#613 feat: Add Nutshell Connector
  providers/nutshell.go
Labels: auth-connector

#703 feat: Enable Write: Intercom
  providers/intercom.go
Labels: auth-integration-testing

#704 fix: DynamicsCRM ListObjectMetadata readable fields only, add DisplayNames
  common/handy/maps.go
  common/json.go
  common/types.go
  dynamicscrm/connector.go
  dynamicscrm/entityAttributes.go
  dynamicscrm/entityDefinition.go
  dynamicscrm/metadata.go
  dynamicscrm/metadata_test.go
  dynamicscrm/models.go
  dynamicscrm/parse.go
  dynamicscrm/read.go
  dynamicscrm/read_test.go
  dynamicscrm/test/contacts-attributes.json
  dynamicscrm/test/contacts-read.json
  dynamicscrm/test/contacts-schema.json
  dynamicscrm/test/metadata.xml
  test/dynamicscrm/metadata/main.go
  test/salesforce/connector.go
Labels: bug

#670 feat: Deep connector Pipeliner (Write)
  pipeliner/delete.go
  pipeliner/delete_test.go
  pipeliner/errors.go
  pipeliner/test/create-entity-validation.json
  pipeliner/test/create-invalid-body.json
  pipeliner/test/create-note.json
  pipeliner/test/delete-note.json
  pipeliner/test/update-note.json
  pipeliner/write.go
  pipeliner/write_test.go
  test/pipeliner/write-delete/main.go
Labels: write-connector

#699 feat: Enable Read+Write: Dynamics CRM
  providers/dynamics.go
Labels: auth-integration-testing

#723 feat: enable proxy: Teamwork connector
  providers/teamwork.go
Labels: auth-integration-testing
